### PR TITLE
Integrating improvements from Konstantinos

### PR DESCRIPTION
**Pull request by dogoepp**
This pull request is rather to formalise that I reviewed the code.

It's good, besides two small issues, phrased as comments in c22fc13 and f148ebc. I can address them, if you agree with my point.

### CODE REVIEW

**Comment by costashatz** [comment]
> This pull request is rather to formalise that I reviewed the code.
> 
> It's good, besides two small issues, phrased as comments in c22fc13 and f148ebc. I can address them, if you agree with my point.

I think you did not PR the proper branch. The upstream version is dyn_v2.

@dogoepp check this #2 instead.

**Comment by dogoepp** [comment]
I purposefully did this with the version still using the v1. I'm starting to read the version for v2 of libdynamixel.

Sorry for the noise.

**Comment by costashatz** [comment]
> I purposefully did this with the version still using the v1. I'm starting to read the version for v2 of libdynamixel.
> 
> Sorry for the noise.

I am ok with it, although I do not see why you should more work than needed. Read v2 and then check the other PR, because we fixed some issues we had.

**Comment by dogoepp** [comment]
Yes, yes you're right on this, of course

**Pull request closed without merging**
