### PR TITLE
Fix bug where one-digit servo IDs are casted into char

### PR DESCRIPTION
**Pull request by naoki-mizuno**
Issue arises when one-digit servo IDs are specified in the YAML file. Since
`Protocol::id_t` is `uint8_t` (a.k.a. `char`), the stream insertion operator `>>`
converts the ID into a `char`. This results in mappings that are not consistent
with the settings in the YAML file. For example,

```yaml
hardware_corrections:
  3: 3.14
```

is interpreted as:

```yaml
hardware_corrections:
  51: 3.14
```

because the ASCII code for `3` is 51. The bug is not apparent when two-digit or three-digit servo IDs are specified because they get converted correctly by the stream insertion operator.

### CODE REVIEW

**Comment by jbmouret** [comment]
Thank you for your pull request. We will review it quickly (and most probably accept it).

**Comment by dogoepp** [comment]
Thanks a lot for this contribution. I took the liberty to directly integrate your commit in the devel branch as I've messed a lot with this branch (having missused the squash and merge feature).

Yet, I cannot reproduce your problem. Should I use integer keys in `hardware_corrections` or `max_speed`, rosparam would complain with this error

```
ERROR: YAML dictionaries must have string keys. Invalid dictionary is:
{'1': 3.14159265359, 26: 3.14159265359, '2': 3.14159265359}
```

So I always quote the servo IDs and never had any issue. Di you have any clue why you face this problem ?

**Comment by naoki-mizuno** [comment]
Thanks for merging!!

> Should I use integer keys

I also noticed that you can't use integers for YAML keys in C++. The YAML specification doesn't limit keys to strings, so maybe this is a limitation in rosparam.

However, the problem is not so much the fact that we can't use integer keys. To better illustrate the problem I wrote the following sample program, which basically converts a string argument (`"3"` and `"26"`) to an integer using the `istringstream` method and the `stoll` method.

```cpp
#include <iostream>
#include <sstream>

namespace Protocol {
    using id_t = uint8_t;
}

Protocol::id_t
read_string_iss(const std::string& s) {
    Protocol::id_t num;
    std::istringstream(s) >> num;
    return num;
}

Protocol::id_t
read_string_stoll(const std::string& s) {
    Protocol::id_t num = std::stoll(s);
    return num;
}

int
main() {
    std::string three = "3";
    std::string twenty_six = "26";

    std::cout << "With std::istringstream" << std::endl;
    std::cout << static_cast<int>(read_string_iss(three)) << std::endl;
    std::cout << static_cast<int>(read_string_iss(twenty_six)) << std::endl;

    std::cout << "With std::stoll" << std::endl;
    std::cout << static_cast<int>(read_string_stoll(three)) << std::endl;
    std::cout << static_cast<int>(read_string_stoll(twenty_six)) << std::endl;
    return 0;
}
```

I found from [`libdynamixel`](https://github.com/resibots/libdynamixel/blob/master/src/dynamixel/protocols/protocol1.hpp#L21) that `Protocol::id_t` is `uint8_t`. When running this program I get the output:

```
With std::istringstream
51
50
With std::stoll
3
26
```

We expected `istringstream` to read `3` and `26` respectively. However, what actually happened is that the first character of `"3"` and `"26"`, which is `'3'` and `'2'` respectively, got read and their character codes `51` and `50` were returned.

It seems like `istringstream` treats the argument differently depending on the type of the variable. In our case, the type was `uint8_t` (which is `char`), so, `istringstream` thought we wanted one character from the string.

What I don't understand though is why the hardware offset was working as expected when using `istringstream`. I initially thought that when giving two-digit strings (like `"26"`) to `istringstream` it knew that we wanted an integer. However, from the sample program, it seems that as long as the type of the destination variable is `uint8_t`, no matter how digits we give to `istringstream`, what's returned is always the first digit's character code... :confused:

**Comment by dogoepp** [comment]
Thanks for your explanation. I can reproduce your observation with the program you wrote, but not in dynamixel_control_hw. Strange...

Anyway, your proposal is sound and integrated so this should no longer be a problem.

**Comment by naoki-mizuno** [comment]
> but not in dynamixel_control_hw

Hmm... that is strange...

We are planning on playing around with the module, so I'll make sure to report here if anything weird happens!

**Comment by dogoepp** [comment]
OK, thanks in advance.

**Pull request closed without merging**
